spring.application.name=ChatRedesBE
spring.datasource.url=jdbc:postgresql://25.32.77.213/redeschatdb
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true